# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
enviroment: development

# Site settings
title: Soopace
email: simonjisu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://simonjisu.github.io" # the base hostname & protocol for your site
logo: "/assets/img/logo.png"
github_username: simonjisu 

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Third-party services
# just leave someone empty to disable it
google_analytics: UA-102691608-1
disqus_shortname: soopace
google_adsense: "ca-pub-5855917513482122"

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->

# font settings
google_fonts: "Nanum+Gothic:400,700"

# menu bar
menu_contents: 
  - title: Home
    url: /
  - title: Posts
    url: /archive
    subposts:
      - subcat: separator
      - subcat: nlp
      - subcat: book
      - subcat: paper
      - subcat: others
      - subcat: programming
      - subcat: datascience
      - subcat: numpyseries
      - subcat: lightseparator
      - subcat: prml
      - subcat: separator
  - title: Abouts
    url: /about
  - title: RSS
    url: /feed.xml

# exclude cache files
exclude:
  - .jekyll-cache